name: Connection tests

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - master
      - main

jobs:
  connection-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the entire history is available

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: '1.28.0'

      - name: Additional setup
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap
          sudo npm install -g svgo
          git config --local user.email "null@github.com"
          git config --local user.name "GitHub Action"

      - name: Perform connection tests
        run: deno run --allow-net --allow-read --allow-write --allow-run --unstable source/tests.ts

      - name: Prepare to commit
        run: |
          npx svgo --multipass -f status
          git add static/site hosts status README.md

      - name: Commit results
        run: |
          git commit -m "Update connection status" || echo "No changes to commit"

      - name: Pull latest changes with rebase
        run: git pull --rebase

      - name: Push changes
        run: git push
