name: Connection tests

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - master
      - main

jobs:
  connection-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: '1.28.0'

      - name: Additional setup
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap
          sudo npm install -g svgo
          git config --local user.email "null@github.com"
          git config --local user.name "GitHub Action"

      - name: Perform connection tests
        run: deno run --allow-net --allow-read --allow-write --allow-run --unstable source/tests.ts

      - name: Optimize SVG files
        run: npx svgo --multipass -f status

      - name: Add changes to Git
        run: git add static/site hosts status README.md

      - name: Commit results
        run: |
          git commit -m "Update connection status" || echo "No changes to commit"

      - name: Forcefully pull and reset to remote state
        run: |
          git fetch origin
          git reset --hard origin/master  # Ensures the local branch matches the remote master branch
          git clean -fdx  # Remove all untracked files and directories

      - name: Push changes
        run: |
          git push origin HEAD:master --force  # Forces the push to the master branch on origin
